{{- $n := include "mailserver.fullname" . -}}
apiVersion: v1
kind: Service
metadata: { name: {{ $n }}-dovecot }
spec:
  selector: { app.kubernetes.io/name: {{ $n }}, app.kubernetes.io/component: dovecot }
  ports:
    - { name: lmtp, port: 24, targetPort: lmtp }
    - { name: imaps, port: 993, targetPort: imaps }
    {{- if .Values.sogo.enabled }}
    - { name: imap-sogo, port: 1143, targetPort: imap-sogo }
    - { name: sieve-sogo, port: 4190, targetPort: sieve-sogo }
    {{- end }}
    - { name: auth, port: 12345, targetPort: auth }
