apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mailserver.fullname" . }}-mail
  labels:
    {{- include "mailserver.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.persistence.mail.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.mail.size }}
