{{- $n := include "mailserver.fullname" . -}}
apiVersion: v1
kind: Service
metadata: { name: {{ $n }}-postfix }
spec:
  publishNotReadyAddresses: true
  selector: { app.kubernetes.io/name: {{ $n }}, app.kubernetes.io/component: postfix }
  ports:
    - { name: http-acme, port: 80, targetPort: http-acme }
    - { name: smtp, port: 25, targetPort: smtp }
    - { name: submissions, port: 465, targetPort: submissions }
    - { name: submission, port: 587, targetPort: submission }

